### ISSUE TITLE
extra forward slash in vessel-install.sh

### ISSUE THREAD

**Issue by dostro** [dfinity/cancan#13]
> BINDIR=$HOME/bin/
> mkdir -p $BINDIR
> BIN=$BINDIR/vessel

`$BIN` results in two forward slashes between `$BINDIR` and `vessel`

I'm a "hobby" developer and don't know if I should open another ticket for this other issue: I ultimately needed to install vessel in the `/usr/local/bin` path instead of `$HOME` - is that just because I don't have that path being searched for these kinds of packages or something similar?

**Comment by ggreif** [comment]
It is generally harmless on POSIX systems, but I have submitted #14 nevertheless. Thanks for the report @dostro!
