### ISSUE TITLE
Error when running `dfx build`

### ISSUE THREAD

**Issue by neeboo** [dfinity/cancan#3]
I got this error:

The build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: Failed to invoke the package tool "vessel" "sources"
 the error was: No such file or directory (os error 2)

**Comment by C-B-Elite** [comment]
try to add the vessel environment path into profile

**Comment by neeboo** [comment]
> try to add the vessel environment path into profile

Fixed it by copying/pasting vessel bin to cancan folder and modify `dfx.json`:

```json
"defaults": {
		"build": {
			"packtool": "./vessel sources",
			"output": "build"
		},

```
