### ISSUE TITLE
Video upload: Error: failed to create video

### ISSUE THREAD

**Issue by msecret** [dfinity/cancan#7]
When attempting to upload a video, I receive the following error in the browser console: `Failed to store video. Error: failed to create video`. 

This only happens when interacting with the app from the canister frontend vs the webpack dev server.

dfx version: dfx 0.7.0-beta.6
browser: chrome 90.0.4430.85 
operating system: macOS 11.2.3

**Comment by taylorham** [comment]
Closed by #11

**Comment by taylorham** [comment]
Closed by #11
